const listaLivros = [
  {
    id: 1,
    nome: " Dom Quixote",
    autor: "Miguel De Cervantes",
    categoria: "romance",
    paginas: 1000,
    recomenda: true,
    leu: true,
  },
  {
    id: 1,
    nome: " Dom Quixote",
    autor: "Miguel De Cervantes",
    categoria: "romance",
    paginas: 1000,
    recomenda: true,
    leu: true,
  },
  {
    id: 2,
    nome: "O Senhor dos Anéis",
    autor: "J. R. R. Tolkien ",
    categoria: "fantasia",
    paginas: 1200,
    recomenda: false,
    leu: false,
  },
  {
    id: 3,
    nome: "Um Conto de Duas Cidades",
    autor: "Charles Dickens",
    categoria: "romance",
    paginas: 380,
    recomenda: false,
    leu: false,
  },
  {
    id: 4,
    nome: "O Pequeno Príncipe",
    autor: "Antoine de Saint-Exupéry ",
    categoria: "literatura para crianças",
    paginas: 490,
    recomenda: false,
    leu: false,
  },
  {
    id: 5,
    nome: "Harry Potter e a Pedra Filosofal,",
    autor: "J.K. Rowling ",
    categoria: "fantasia",
    paginas: 740,
    recomenda: false,
    leu: true,
  },
];
module.exports = listaLivros;
